baseurl = "https://lexingtonfriends.org/"
languageCode = "en-us"
title = "Lexington Friends Meeting (Quaker)"
canonifyurls = false

[[menu.main]]
  name = "About Us"
  identifier = "about"
  weight = 40
  url = "/about/"

[[menu.main]]
  name = "Activities"
  identifier = "activities"
  url = "/calendar/"
  weight = 60

[params]
  metaDescription = "Lexington Friends Meeting (Quaker), Religious Society of Friends, is part of the Ohio Yearly Meeting (OVYM) and Friends General Conference (FGC) and located in Lexington, Kentucky."
  metaKeywords = "Friends, Monthly Meeting, Quaker, Quakers, Religious Society of Friends, Ohio Valley Yearly Meeting, OVYM, Friends General Conference, FGC, Lexington, Kentucky"
  fathomAnalytics = "TUUYHCTC"

[markup.goldmark.renderer]
  unsafe = true
