baseurl: "https://lexingtonfriends.org/"
languageCode: "en-us"
title: "Lexington Friends Meeting (Quaker)"
canonifyurls: false
googleAnalytics: UA-76746700-1

menu:
  main:
    - Name: "About Us"
      Identifier: "about"
      Weight: 40
    - Name: "Activities"
      Identifier: "activities"
      URL: "/calendar"
      Weight: 60

params:
  metaDescription: "Lexington Friends Meeting (Quaker), Religious Society of Friends, is associated part of the Ohio Yearly Meeting (OVYM) and Friends General Conference (FGC) and located in Lexington, Kentucky."
  metaKeywords: "Friends, Monthly Meeting, Quaker, Quakers, Religious Society of Friends, Ohio Valley Yearly Meeting, OVYM, Friends General Conference, FGC, Lexington, Kentucky"
