baseurl: "https://lexingtonfriends.org/"
languageCode: "en-us"
title: "Lexington Friends Meeting (Quaker)"
canonifyurls: false

deployment:
  targets:
    - name: S3
      URL: s3://lexingtonfriends.org?region=us-east-1

menu:
  main:
    - name: About Us
      identifier: about
      weight: 40
      url: /about/
    - name: Activities
      identifier: activities
      url: /calendar/
      weight: 60

params:
  metaDescription: "Lexington Friends Meeting (Quaker), Religious Society of Friends, is part of the Ohio Yearly Meeting (OVYM) and Friends General Conference (FGC) and located in Lexington, Kentucky."
  metaKeywords: "Friends, Monthly Meeting, Quaker, Quakers, Religious Society of Friends, Ohio Valley Yearly Meeting, OVYM, Friends General Conference, FGC, Lexington, Kentucky"
  fathomAnalytics: "TUUYHCTC"
